syntax = "proto3";

package Example.Library;

option csharp_namespace = "Example.Library.Book.Dto.Proto";

// Book represents a book and its metadata for the library, e.g., for search results
message Book {
  // The 13-digit ISBN
  string isbn13 = 1;

  // The title of the book (1-200 characters)
  string title = 2;

  // WebP image of the book cover thumbnail
  optional bytes cover_thumbnail_webp = 3;

  // List of authors of the book (at least one author)
  repeated Author authors = 4;

  // The number of text positions in the book (non-negative integer)
  uint32 number_of_text_position = 5;

  // The main category of the book
  Category category = 6;

  // List of tags associated with the book (up to 20 unique tags, 1-50 characters each)
  repeated string tags = 7;

  // The average rating of the book (0 to 5 stars, with one decimal place)
  optional float rating = 8;

  // Indicates whether the library has a valid license for the book at the moment
  bool has_valid_license = 9;

  // The date when the book was published, in ISO 8601 format (YYYY-MM-DD)
  // This format allows for representation of dates before the Unix epoch
  // Examples: "2000-01-01", "1850-12-25", "0001-01-01"
  string publishing_date = 10;

  // Author represents an author of a book
  message Author {
    // The full name of the author with titles (1-100 characters)
    // Examples: "Eric Evans", "Dr. John Smith"
    string name = 1;

    // WebP image of the author's portrait thumbnail
    optional bytes portrait_thumbnail_webp = 2;
  }

  // Category represents the main category of a book
  enum Category {
    CATEGORY_NON_FICTION = 0;
    CATEGORY_FICTION = 1;
  }
}
