// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: book.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Example.Library.Book.Dto.Proto {

  /// <summary>Holder for reflection information generated from book.proto</summary>
  public static partial class BookReflection {

    #region Descriptor
    /// <summary>File descriptor for book.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BookReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgpib29rLnByb3RvEg9FeGFtcGxlLkxpYnJhcnki2wMKBEJvb2sSDgoGaXNi",
            "bjEzGAEgASgJEg0KBXRpdGxlGAIgASgJEiEKFGNvdmVyX3RodW1ibmFpbF93",
            "ZWJwGAMgASgMSACIAQESLQoHYXV0aG9ycxgEIAMoCzIcLkV4YW1wbGUuTGli",
            "cmFyeS5Cb29rLkF1dGhvchIfChdudW1iZXJfb2ZfdGV4dF9wb3NpdGlvbhgF",
            "IAEoDRIwCghjYXRlZ29yeRgGIAEoDjIeLkV4YW1wbGUuTGlicmFyeS5Cb29r",
            "LkNhdGVnb3J5EgwKBHRhZ3MYByADKAkSEwoGcmF0aW5nGAggASgCSAGIAQES",
            "GQoRaGFzX3ZhbGlkX2xpY2Vuc2UYCSABKAgSFwoPcHVibGlzaGluZ19kYXRl",
            "GAogASgJGlgKBkF1dGhvchIMCgRuYW1lGAEgASgJEiQKF3BvcnRyYWl0X3Ro",
            "dW1ibmFpbF93ZWJwGAIgASgMSACIAQFCGgoYX3BvcnRyYWl0X3RodW1ibmFp",
            "bF93ZWJwIjoKCENhdGVnb3J5EhgKFENBVEVHT1JZX05PTl9GSUNUSU9OEAAS",
            "FAoQQ0FURUdPUllfRklDVElPThABQhcKFV9jb3Zlcl90aHVtYm5haWxfd2Vi",
            "cEIJCgdfcmF0aW5nQiGqAh5FeGFtcGxlLkxpYnJhcnkuQm9vay5EdG8uUHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Example.Library.Book.Dto.Proto.Book), global::Example.Library.Book.Dto.Proto.Book.Parser, new[]{ "Isbn13", "Title", "CoverThumbnailWebp", "Authors", "NumberOfTextPosition", "Category", "Tags", "Rating", "HasValidLicense", "PublishingDate" }, new[]{ "CoverThumbnailWebp", "Rating" }, new[]{ typeof(global::Example.Library.Book.Dto.Proto.Book.Types.Category) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Example.Library.Book.Dto.Proto.Book.Types.Author), global::Example.Library.Book.Dto.Proto.Book.Types.Author.Parser, new[]{ "Name", "PortraitThumbnailWebp" }, new[]{ "PortraitThumbnailWebp" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Book represents a book and its metadata for the library, e.g., for search results
  /// </summary>
  public sealed partial class Book : pb::IMessage<Book>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Book> _parser = new pb::MessageParser<Book>(() => new Book());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Book> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Example.Library.Book.Dto.Proto.BookReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Book() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Book(Book other) : this() {
      _hasBits0 = other._hasBits0;
      isbn13_ = other.isbn13_;
      title_ = other.title_;
      coverThumbnailWebp_ = other.coverThumbnailWebp_;
      authors_ = other.authors_.Clone();
      numberOfTextPosition_ = other.numberOfTextPosition_;
      category_ = other.category_;
      tags_ = other.tags_.Clone();
      rating_ = other.rating_;
      hasValidLicense_ = other.hasValidLicense_;
      publishingDate_ = other.publishingDate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Book Clone() {
      return new Book(this);
    }

    /// <summary>Field number for the "isbn13" field.</summary>
    public const int Isbn13FieldNumber = 1;
    private string isbn13_ = "";
    /// <summary>
    /// The 13-digit ISBN
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Isbn13 {
      get { return isbn13_; }
      set {
        isbn13_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    /// <summary>
    /// The title of the book (1-200 characters)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cover_thumbnail_webp" field.</summary>
    public const int CoverThumbnailWebpFieldNumber = 3;
    private pb::ByteString coverThumbnailWebp_;
    /// <summary>
    /// WebP image of the book cover thumbnail
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CoverThumbnailWebp {
      get { return coverThumbnailWebp_ ?? pb::ByteString.Empty; }
      set {
        coverThumbnailWebp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "cover_thumbnail_webp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCoverThumbnailWebp {
      get { return coverThumbnailWebp_ != null; }
    }
    /// <summary>Clears the value of the "cover_thumbnail_webp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCoverThumbnailWebp() {
      coverThumbnailWebp_ = null;
    }

    /// <summary>Field number for the "authors" field.</summary>
    public const int AuthorsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Example.Library.Book.Dto.Proto.Book.Types.Author> _repeated_authors_codec
        = pb::FieldCodec.ForMessage(34, global::Example.Library.Book.Dto.Proto.Book.Types.Author.Parser);
    private readonly pbc::RepeatedField<global::Example.Library.Book.Dto.Proto.Book.Types.Author> authors_ = new pbc::RepeatedField<global::Example.Library.Book.Dto.Proto.Book.Types.Author>();
    /// <summary>
    /// List of authors of the book (at least one author)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Example.Library.Book.Dto.Proto.Book.Types.Author> Authors {
      get { return authors_; }
    }

    /// <summary>Field number for the "number_of_text_position" field.</summary>
    public const int NumberOfTextPositionFieldNumber = 5;
    private uint numberOfTextPosition_;
    /// <summary>
    /// The number of text positions in the book (non-negative integer)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumberOfTextPosition {
      get { return numberOfTextPosition_; }
      set {
        numberOfTextPosition_ = value;
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 6;
    private global::Example.Library.Book.Dto.Proto.Book.Types.Category category_ = global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction;
    /// <summary>
    /// The main category of the book
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Example.Library.Book.Dto.Proto.Book.Types.Category Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of tags associated with the book (up to 20 unique tags, 1-50 characters each)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "rating" field.</summary>
    public const int RatingFieldNumber = 8;
    private float rating_;
    /// <summary>
    /// The average rating of the book (0 to 5 stars, with one decimal place)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rating {
      get { if ((_hasBits0 & 1) != 0) { return rating_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        rating_ = value;
      }
    }
    /// <summary>Gets whether the "rating" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRating {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "rating" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRating() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "has_valid_license" field.</summary>
    public const int HasValidLicenseFieldNumber = 9;
    private bool hasValidLicense_;
    /// <summary>
    /// Indicates whether the library has a valid license for the book at the moment
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValidLicense {
      get { return hasValidLicense_; }
      set {
        hasValidLicense_ = value;
      }
    }

    /// <summary>Field number for the "publishing_date" field.</summary>
    public const int PublishingDateFieldNumber = 10;
    private string publishingDate_ = "";
    /// <summary>
    /// The date when the book was published, in ISO 8601 format (YYYY-MM-DD)
    /// This format allows for representation of dates before the Unix epoch
    /// Examples: "2000-01-01", "1850-12-25", "0001-01-01"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublishingDate {
      get { return publishingDate_; }
      set {
        publishingDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Book);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Book other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Isbn13 != other.Isbn13) return false;
      if (Title != other.Title) return false;
      if (CoverThumbnailWebp != other.CoverThumbnailWebp) return false;
      if(!authors_.Equals(other.authors_)) return false;
      if (NumberOfTextPosition != other.NumberOfTextPosition) return false;
      if (Category != other.Category) return false;
      if(!tags_.Equals(other.tags_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rating, other.Rating)) return false;
      if (HasValidLicense != other.HasValidLicense) return false;
      if (PublishingDate != other.PublishingDate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Isbn13.Length != 0) hash ^= Isbn13.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (HasCoverThumbnailWebp) hash ^= CoverThumbnailWebp.GetHashCode();
      hash ^= authors_.GetHashCode();
      if (NumberOfTextPosition != 0) hash ^= NumberOfTextPosition.GetHashCode();
      if (Category != global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction) hash ^= Category.GetHashCode();
      hash ^= tags_.GetHashCode();
      if (HasRating) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rating);
      if (HasValidLicense != false) hash ^= HasValidLicense.GetHashCode();
      if (PublishingDate.Length != 0) hash ^= PublishingDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Isbn13.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Isbn13);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (HasCoverThumbnailWebp) {
        output.WriteRawTag(26);
        output.WriteBytes(CoverThumbnailWebp);
      }
      authors_.WriteTo(output, _repeated_authors_codec);
      if (NumberOfTextPosition != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(NumberOfTextPosition);
      }
      if (Category != global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Category);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      if (HasRating) {
        output.WriteRawTag(69);
        output.WriteFloat(Rating);
      }
      if (HasValidLicense != false) {
        output.WriteRawTag(72);
        output.WriteBool(HasValidLicense);
      }
      if (PublishingDate.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PublishingDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Isbn13.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Isbn13);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (HasCoverThumbnailWebp) {
        output.WriteRawTag(26);
        output.WriteBytes(CoverThumbnailWebp);
      }
      authors_.WriteTo(ref output, _repeated_authors_codec);
      if (NumberOfTextPosition != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(NumberOfTextPosition);
      }
      if (Category != global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Category);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (HasRating) {
        output.WriteRawTag(69);
        output.WriteFloat(Rating);
      }
      if (HasValidLicense != false) {
        output.WriteRawTag(72);
        output.WriteBool(HasValidLicense);
      }
      if (PublishingDate.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PublishingDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Isbn13.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Isbn13);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (HasCoverThumbnailWebp) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CoverThumbnailWebp);
      }
      size += authors_.CalculateSize(_repeated_authors_codec);
      if (NumberOfTextPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberOfTextPosition);
      }
      if (Category != global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (HasRating) {
        size += 1 + 4;
      }
      if (HasValidLicense != false) {
        size += 1 + 1;
      }
      if (PublishingDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublishingDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Book other) {
      if (other == null) {
        return;
      }
      if (other.Isbn13.Length != 0) {
        Isbn13 = other.Isbn13;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.HasCoverThumbnailWebp) {
        CoverThumbnailWebp = other.CoverThumbnailWebp;
      }
      authors_.Add(other.authors_);
      if (other.NumberOfTextPosition != 0) {
        NumberOfTextPosition = other.NumberOfTextPosition;
      }
      if (other.Category != global::Example.Library.Book.Dto.Proto.Book.Types.Category.NonFiction) {
        Category = other.Category;
      }
      tags_.Add(other.tags_);
      if (other.HasRating) {
        Rating = other.Rating;
      }
      if (other.HasValidLicense != false) {
        HasValidLicense = other.HasValidLicense;
      }
      if (other.PublishingDate.Length != 0) {
        PublishingDate = other.PublishingDate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Isbn13 = input.ReadString();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            CoverThumbnailWebp = input.ReadBytes();
            break;
          }
          case 34: {
            authors_.AddEntriesFrom(input, _repeated_authors_codec);
            break;
          }
          case 40: {
            NumberOfTextPosition = input.ReadUInt32();
            break;
          }
          case 48: {
            Category = (global::Example.Library.Book.Dto.Proto.Book.Types.Category) input.ReadEnum();
            break;
          }
          case 58: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 69: {
            Rating = input.ReadFloat();
            break;
          }
          case 72: {
            HasValidLicense = input.ReadBool();
            break;
          }
          case 82: {
            PublishingDate = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Isbn13 = input.ReadString();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            CoverThumbnailWebp = input.ReadBytes();
            break;
          }
          case 34: {
            authors_.AddEntriesFrom(ref input, _repeated_authors_codec);
            break;
          }
          case 40: {
            NumberOfTextPosition = input.ReadUInt32();
            break;
          }
          case 48: {
            Category = (global::Example.Library.Book.Dto.Proto.Book.Types.Category) input.ReadEnum();
            break;
          }
          case 58: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 69: {
            Rating = input.ReadFloat();
            break;
          }
          case 72: {
            HasValidLicense = input.ReadBool();
            break;
          }
          case 82: {
            PublishingDate = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Book message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Category represents the main category of a book
      /// </summary>
      public enum Category {
        [pbr::OriginalName("CATEGORY_NON_FICTION")] NonFiction = 0,
        [pbr::OriginalName("CATEGORY_FICTION")] Fiction = 1,
      }

      /// <summary>
      /// Author represents an author of a book
      /// </summary>
      public sealed partial class Author : pb::IMessage<Author>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Author> _parser = new pb::MessageParser<Author>(() => new Author());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Author> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Example.Library.Book.Dto.Proto.Book.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Author() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Author(Author other) : this() {
          name_ = other.name_;
          portraitThumbnailWebp_ = other.portraitThumbnailWebp_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Author Clone() {
          return new Author(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        /// <summary>
        /// The full name of the author with titles (1-100 characters)
        /// Examples: "Eric Evans", "Dr. John Smith"
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "portrait_thumbnail_webp" field.</summary>
        public const int PortraitThumbnailWebpFieldNumber = 2;
        private pb::ByteString portraitThumbnailWebp_;
        /// <summary>
        /// WebP image of the author's portrait thumbnail
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString PortraitThumbnailWebp {
          get { return portraitThumbnailWebp_ ?? pb::ByteString.Empty; }
          set {
            portraitThumbnailWebp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "portrait_thumbnail_webp" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasPortraitThumbnailWebp {
          get { return portraitThumbnailWebp_ != null; }
        }
        /// <summary>Clears the value of the "portrait_thumbnail_webp" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearPortraitThumbnailWebp() {
          portraitThumbnailWebp_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Author);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Author other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (PortraitThumbnailWebp != other.PortraitThumbnailWebp) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (HasPortraitThumbnailWebp) hash ^= PortraitThumbnailWebp.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (HasPortraitThumbnailWebp) {
            output.WriteRawTag(18);
            output.WriteBytes(PortraitThumbnailWebp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (HasPortraitThumbnailWebp) {
            output.WriteRawTag(18);
            output.WriteBytes(PortraitThumbnailWebp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (HasPortraitThumbnailWebp) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(PortraitThumbnailWebp);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Author other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.HasPortraitThumbnailWebp) {
            PortraitThumbnailWebp = other.PortraitThumbnailWebp;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                PortraitThumbnailWebp = input.ReadBytes();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                PortraitThumbnailWebp = input.ReadBytes();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
