FROM eclipse-temurin:8-jre

RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -L -O https://github.com/rkluszczynski/avro-cli/releases/download/avro-cli-0.2.7/avro-cli-0.2.7.jar

# ENTRYPOINT java -jar avro-cli-0.2.7.jar 

