//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Example.Library.Book.Dto.Json
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A schema representing a book and its metadata for the library for, e.g., search results
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Book
    {
        /// <summary>
        /// The 13-digit ISBN
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("isbn13")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9]{13}$")]
        public string Isbn13 { get; set; }

        /// <summary>
        /// The title of the book
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Title { get; set; }

        /// <summary>
        /// Base64 encoded WebP image of the book cover thumbnail
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("coverThumbnailWebP")]
        public string CoverThumbnailWebP { get; set; }

        /// <summary>
        /// List of authors of the book
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("authors")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<Authors> Authors { get; set; } = new System.Collections.ObjectModel.Collection<Authors>();

        /// <summary>
        /// The number of text position in the book
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("numberOfTextPosition")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int NumberOfTextPosition { get; set; }

        /// <summary>
        /// The main category of the book
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("category")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public BookCategory Category { get; set; }

        /// <summary>
        /// List of tags associated with the book (top 20)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("tags")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MaxLength(20)]
        public System.Collections.Generic.ICollection<string> Tags { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        /// <summary>
        /// The average rating of the book (0 to 5 stars, with one decimal place)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rating")]
        [System.ComponentModel.DataAnnotations.Range(0D, 5D)]
        public double Rating { get; set; }

        /// <summary>
        /// Indicates whether the library has a valid license for the book at the moment
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("hasValidLicense")]
        public bool HasValidLicense { get; set; }

        /// <summary>
        /// The date when the book was published
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("publishingDate")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset PublishingDate { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Authors
    {
        /// <summary>
        /// The full name of the author with titles
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 1)]
        public string Name { get; set; }

        /// <summary>
        /// Base64 encoded WebP image of the author's portrait thumbnail
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("portraitThumbnailWebP")]
        public string PortraitThumbnailWebP { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum BookCategory
    {

        [System.Runtime.Serialization.EnumMember(Value = @"NON_FICTION")]
        NON_FICTION = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"FICTION")]
        FICTION = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
    {
        public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTimeOffset.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }
}