// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Example.Library.Book.Dto.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Author : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Author"",""namespace"":""Example.Library.Book.Dto.Avro"",""fields"":[{""name"":""name"",""doc"":""The full name of the author with titles, e.g.: \""Eric Evans\"", \""Dr. John Smith\"""",""type"":""string""},{""name"":""portraitThumbnailWebP"",""doc"":""Base64 encoded WebP image of the author's portrait thumbnail"",""default"":null,""type"":[""null"",""bytes""]}]}");
		/// <summary>
		/// The full name of the author with titles, e.g.: "Eric Evans", "Dr. John Smith"
		/// </summary>
		private string _name;
		/// <summary>
		/// Base64 encoded WebP image of the author's portrait thumbnail
		/// </summary>
		private byte[] _portraitThumbnailWebP;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Author._SCHEMA;
			}
		}
		/// <summary>
		/// The full name of the author with titles, e.g.: "Eric Evans", "Dr. John Smith"
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		/// <summary>
		/// Base64 encoded WebP image of the author's portrait thumbnail
		/// </summary>
		public byte[] portraitThumbnailWebP
		{
			get
			{
				return this._portraitThumbnailWebP;
			}
			set
			{
				this._portraitThumbnailWebP = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.portraitThumbnailWebP;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.portraitThumbnailWebP = (System.Byte[])fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
