// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Example.Library.Book.Dto.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// A schema representing a book and its metadata for the library for, e.g., search results
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Book : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Book\",\"doc\":\"A schema representing a book and its metada" +
				"ta for the library for, e.g., search results\",\"namespace\":\"Example.Library.Book." +
				"Dto.Avro\",\"fields\":[{\"name\":\"isbn13\",\"doc\":\"The 13-digit ISBN, e.g., 97812345678" +
				"90\",\"type\":\"string\"},{\"name\":\"title\",\"doc\":\"The title of the book\",\"type\":\"strin" +
				"g\"},{\"name\":\"coverThumbnailWebP\",\"doc\":\"Base64 encoded WebP image of the book co" +
				"ver thumbnail\",\"default\":null,\"type\":[\"null\",\"bytes\"]},{\"name\":\"authors\",\"doc\":\"" +
				"List of authors of the book\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"na" +
				"me\":\"Author\",\"namespace\":\"Example.Library.Book.Dto.Avro\",\"fields\":[{\"name\":\"name" +
				"\",\"doc\":\"The full name of the author with titles, e.g.: \\\"Eric Evans\\\", \\\"Dr. Jo" +
				"hn Smith\\\"\",\"type\":\"string\"},{\"name\":\"portraitThumbnailWebP\",\"doc\":\"Base64 encod" +
				"ed WebP image of the author\'s portrait thumbnail\",\"default\":null,\"type\":[\"null\"," +
				"\"bytes\"]}]}}},{\"name\":\"numberOfTextPosition\",\"doc\":\"The number of text position " +
				"in the book\",\"type\":\"long\"},{\"name\":\"category\",\"doc\":\"The main category of the b" +
				"ook\",\"type\":{\"type\":\"enum\",\"name\":\"Category\",\"namespace\":\"Example.Library.Book.D" +
				"to.Avro\",\"symbols\":[\"NON_FICTION\",\"FICTION\"]}},{\"name\":\"tags\",\"doc\":\"List of tag" +
				"s associated with the book (top 20)\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{" +
				"\"name\":\"rating\",\"doc\":\"The average rating of the book (0 to 5 stars, with one de" +
				"cimal place), e.g., 4.5\",\"default\":null,\"type\":[\"null\",\"bytes\"],\"precision\":2,\"s" +
				"cale\":1},{\"name\":\"hasValidLicense\",\"doc\":\"Indicates whether the library has a va" +
				"lid license for the book at the moment\",\"default\":true,\"type\":\"boolean\"},{\"name\"" +
				":\"publishingDate\",\"doc\":\"The date when the book was published in yyyy-mm-dd form" +
				"at ([Date](https://avro.apache.org/docs/1.8.0/spec.html#Date) was not used as it" +
				" does not allow to store values before the unix epoch, 1 January 1970)\",\"type\":{" +
				"\"type\":\"string\",\"pattern\":\"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\"}}]}");
		/// <summary>
		/// The 13-digit ISBN, e.g., 9781234567890
		/// </summary>
		private string _isbn13;
		/// <summary>
		/// The title of the book
		/// </summary>
		private string _title;
		/// <summary>
		/// Base64 encoded WebP image of the book cover thumbnail
		/// </summary>
		private byte[] _coverThumbnailWebP;
		/// <summary>
		/// List of authors of the book
		/// </summary>
		private IList<Example.Library.Book.Dto.Avro.Author> _authors;
		/// <summary>
		/// The number of text position in the book
		/// </summary>
		private long _numberOfTextPosition;
		/// <summary>
		/// The main category of the book
		/// </summary>
		private Example.Library.Book.Dto.Avro.Category _category;
		/// <summary>
		/// List of tags associated with the book (top 20)
		/// </summary>
		private IList<System.String> _tags;
		/// <summary>
		/// The average rating of the book (0 to 5 stars, with one decimal place), e.g., 4.5
		/// </summary>
		private byte[] _rating;
		/// <summary>
		/// Indicates whether the library has a valid license for the book at the moment
		/// </summary>
		private bool _hasValidLicense;
		/// <summary>
		/// The date when the book was published in yyyy-mm-dd format ([Date](https://avro.apache.org/docs/1.8.0/spec.html#Date) was not used as it does not allow to store values before the unix epoch, 1 January 1970)
		/// </summary>
		private string _publishingDate;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Book._SCHEMA;
			}
		}
		/// <summary>
		/// The 13-digit ISBN, e.g., 9781234567890
		/// </summary>
		public string isbn13
		{
			get
			{
				return this._isbn13;
			}
			set
			{
				this._isbn13 = value;
			}
		}
		/// <summary>
		/// The title of the book
		/// </summary>
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		/// <summary>
		/// Base64 encoded WebP image of the book cover thumbnail
		/// </summary>
		public byte[] coverThumbnailWebP
		{
			get
			{
				return this._coverThumbnailWebP;
			}
			set
			{
				this._coverThumbnailWebP = value;
			}
		}
		/// <summary>
		/// List of authors of the book
		/// </summary>
		public IList<Example.Library.Book.Dto.Avro.Author> authors
		{
			get
			{
				return this._authors;
			}
			set
			{
				this._authors = value;
			}
		}
		/// <summary>
		/// The number of text position in the book
		/// </summary>
		public long numberOfTextPosition
		{
			get
			{
				return this._numberOfTextPosition;
			}
			set
			{
				this._numberOfTextPosition = value;
			}
		}
		/// <summary>
		/// The main category of the book
		/// </summary>
		public Example.Library.Book.Dto.Avro.Category category
		{
			get
			{
				return this._category;
			}
			set
			{
				this._category = value;
			}
		}
		/// <summary>
		/// List of tags associated with the book (top 20)
		/// </summary>
		public IList<System.String> tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				this._tags = value;
			}
		}
		/// <summary>
		/// The average rating of the book (0 to 5 stars, with one decimal place), e.g., 4.5
		/// </summary>
		public byte[] rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				this._rating = value;
			}
		}
		/// <summary>
		/// Indicates whether the library has a valid license for the book at the moment
		/// </summary>
		public bool hasValidLicense
		{
			get
			{
				return this._hasValidLicense;
			}
			set
			{
				this._hasValidLicense = value;
			}
		}
		/// <summary>
		/// The date when the book was published in yyyy-mm-dd format ([Date](https://avro.apache.org/docs/1.8.0/spec.html#Date) was not used as it does not allow to store values before the unix epoch, 1 January 1970)
		/// </summary>
		public string publishingDate
		{
			get
			{
				return this._publishingDate;
			}
			set
			{
				this._publishingDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.isbn13;
			case 1: return this.title;
			case 2: return this.coverThumbnailWebP;
			case 3: return this.authors;
			case 4: return this.numberOfTextPosition;
			case 5: return this.category;
			case 6: return this.tags;
			case 7: return this.rating;
			case 8: return this.hasValidLicense;
			case 9: return this.publishingDate;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.isbn13 = (System.String)fieldValue; break;
			case 1: this.title = (System.String)fieldValue; break;
			case 2: this.coverThumbnailWebP = (System.Byte[])fieldValue; break;
			case 3: this.authors = (IList<Example.Library.Book.Dto.Avro.Author>)fieldValue; break;
			case 4: this.numberOfTextPosition = (System.Int64)fieldValue; break;
			case 5: this.category = (Example.Library.Book.Dto.Avro.Category)fieldValue; break;
			case 6: this.tags = (IList<System.String>)fieldValue; break;
			case 7: this.rating = (System.Byte[])fieldValue; break;
			case 8: this.hasValidLicense = (System.Boolean)fieldValue; break;
			case 9: this.publishingDate = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
