name: Validate

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  validate-jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-jsonschema

  validate-avro-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-avro-schema

  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-xml

  validate-protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-protobuf

  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-openapi

  validate-asyncapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run validate-asyncapi

